spring.profiles.active=dev

# HikariCP 데이터소스 및 데이터베이스 설정
spring.datasource.hikari.driver-class-name=${DBMS_DRIVER}
spring.datasource.hikari.jdbc-url=${DBMS_URL}
spring.datasource.hikari.username=${DBMS_USERNAME}
spring.datasource.hikari.password=${DBMS_PW}
spring.datasource.hikari.connection-test-query=SELECT sysdate FROM DUAL

# JPA 설정
spring.jpa.database=oracle
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false

# 파일 업로드 설정
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB

# HTTP 커넥터 파트 개수 제한
# 스프링부트 3.5.1부터 적용된 보안 취약점 Patch로 인해 multipart/form-data 요청에 포함될 수 있는 최대 파트 수(maxPartCount)가 기본값 10개로 제한
# 즉, 전송된 폼 필드와 파일의 총합이 10개를 초과하면 org.apache.tomcat.util.http.fileupload.impl.FileCountLimitExceededException 에러 발생
# multipart/form-data 요청에서 업로드 가능한 파트(part)의 최대 개수
server.tomcat.max-part-count=100
# HTTP 요청 파라미터의 최대 개수. HTTP 요청 파라미터는 브라우저가 서버에 보내는 이름=값(name=value) 형태의 데이터
server.tomcat.max-parameter-count=10000

# JSON 설정
spring.jackson.serialization.fail-on-empty-beans=false

# 운영 환경 안정성을 위해 편의 기능 비활성화 및 캐시 활성화
#spring.devtools.livereload.enabled=true
#spring.thymeleaf.cache=false

# 톰캣 설정
tomcat.ajp.protocol=AJP/1.3
tomcat.ajp.port=8009
tomcat.ajp.enabled=true

#JWT secret 설정
jwt.secret=BoardRestBoardRestBoardRestBoardRestBoardRestBoardRestBoardRestBoardRestBoardRestBoardRest


# =============================================
# OpenAI API 설정
# =============================================
spring.application.name=ChatBot
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.4-mini

# =============================================
# OpenWeatherMap API ì¤ì  (https://openweathermap.org)
# =============================================
external.api.weather.key=${OPENWEATHERMAP_API_KEY}

# =============================================
# SerpApi 설정(https://serpapi.com)
# =============================================
external.api.serp.key=${SERP_API_KEY}
