apiVersion: v1
kind: ConfigMap
metadata:
  name: boardnext-config
data:
  DBMS_URL: "jdbc:oracle:thin:@//192.168.0.112:1521/springpdb"
  DBMS_DRIVER: "oracle.jdbc.driver.OracleDriver"
  DBMS_USERNAME: "springdev"
  OPENWEATHERMAP_API_KEY: "45877e68514c84bcb209ac4c33b6b501344415941313a73c935327126f05dae0"
