# 1. 정적 PV 3개 생성
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-0
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-storage
  hostPath:
    path: /var/opt/kafka-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-1
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-storage
  hostPath:
    path: /var/opt/kafka-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-2
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-storage
  hostPath:
    path: /var/opt/kafka-2
---
# 2. 멀티 노드용 Kafka 노드풀
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - broker
    - controller
  template:
    pod:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 500Mi
        class: kafka-storage
---
# 3. Kafka 클러스터 설정
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.3.0
    metadataVersion: 4.3-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 31090
          brokers:
            - broker: 0
              advertisedHost: 192.168.20.2
              nodePort: 31091
            - broker: 1
              advertisedHost: 192.168.20.2
              nodePort: 31092
            - broker: 2
              advertisedHost: 192.168.20.2
              nodePort: 31093
  entityOperator:
    topicOperator: {}
    userOperator: {}